add a generic evolver for genomes (#43)
* requires nim-1.7 i guess

* rm warning

* rm warning

* guards

* vendor a heapqueue with configurable comparison

* refactor for heapqueue-based operators

* add a removal for heapqueue populations

* tournament for heapqueue populations

* export VM maintenance routine

* rm spam

* paint the program and then introduce it

* dump genome hash

* simplify

* wip genome-based evolution

* simplify

* randomize the entire genome 🙄

* simplify

* fix off-by-one, add guard for short genomes

* simplify

* reorganize types

* fix canRead()

* complexify

* genome removal uses a tournament, also

* shutdown via the output mailbox

* embrace large genomes

* cosmetic

* rm spam

* rm spam

* cosmetic

* dialing in the example

* program length really is genome length

* relax restrictions on ranges

* add asym crossover operators

* remove a broken bare break

* rm string dependency

* unify examples with a preamble

* good enough indeed

* tighten up more strings

* trim sharing to a rational level

* simplify

* simplify

* rm warnings

* you were right the first time

* update tests

* fix leak in lua parsing

* useMalloc in ci

* rm unused imports

* rm possible race

* sinks and stuff

* smaller mailboxes

* add obvious overload

* more (and less) code reuse

* belt and suspenders on render status

* old code commit

* rework the closure-over-cache approach

* tweak ci

* tweak docs, ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -35,9 +35,9 @@ jobs:
     runs-on: ${{ matrix.os }}
     steps:
       - name: Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
         with:
-          path: ci
+          path: project
 
       - name: Setup Nim
         uses: alaviss/setup-nim@0.1.1
@@ -64,32 +64,32 @@ jobs:
       - name: Run tests
         shell: bash
         run: |
-          cd ci
+          cd project
           nimble --accept develop
-          nimble --accept install "https://github.com/disruptek/balls@#4.0.8"
-          balls --define:release --define:danger --mm:arc --backend:c
+          nimble --accept install "https://github.com/disruptek/balls"
+          balls --path="\$projectdir" --define:release --define:danger --mm:arc --backend:c --define:useMalloc
 
-      - name: Build docs
-        if: ${{ matrix.docs }} == 'true'
-        shell: bash
-        run: |
-          cd ci
-          branch=${{ github.ref }}
-          branch=${branch##*/}
-          nimble doc --gc:arc --threads:on --project --path="." --outdir:docs \
-            '--git.url:https://github.com/${{ github.repository }}' \
-            '--git.commit:${{ github.sha }}' \
-            "--git.devel:$branch" \
-            gread.nim
-          # Ignore failures for older Nim
-          cp docs/{the,}index.html || true
+      # - name: Build docs
+      #   if: ${{ matrix.docs }} == 'true'
+      #   shell: bash
+      #   run: |
+      #     cd project
+      #     branch=${{ github.ref }}
+      #     branch=${branch##*/}
+      #     nimble doc --gc:arc --threads:on --project --path="." --outdir:docs \
+      #       '--git.url:https://github.com/${{ github.repository }}' \
+      #       '--git.commit:${{ github.sha }}' \
+      #       "--git.devel:$branch" \
+      #       gread.nim
+      #     # Ignore failures for older Nim
+      #     cp docs/{the,}index.html || true
 
-      - name: Publish docs
-        if: >
-          github.event_name == 'push' && github.ref == 'refs/heads/main' &&
-          matrix.os == 'ubuntu-latest' && matrix.nim == 'version-2-0'
-        uses: crazy-max/ghaction-github-pages@v1
-        with:
-          build_dir: ci/docs
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Publish docs
+      #   if: >
+      #     github.event_name == 'push' && github.ref == 'refs/heads/main' &&
+      #     matrix.os == 'ubuntu-latest' && matrix.nim == 'version-2-0'
+      #   uses: crazy-max/ghaction-github-pages@v1
+      #   with:
+      #     build_dir: project/docs
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
